version: '3.8'
## Services
services:

  ## PHP
  php:
    container_name: cw_php
    build:
      context: ./php
      dockerfile: Dockerfile
      ## These define the host user within the container
      args:
        USER: dev
        USER_ID: 1000
        GROUP_ID: 1000
    env_file:
      - ./env/php.env
    volumes:
      - ./project:/var/www/html
    configs:
      - source: phplocal
        target: /usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - cw_network

  ## PostgreSQL
  postgresql:
    container_name: cw_postgresql
    image: postgres:14-alpine
    user: root
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgresql.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - postgresdata:/var/lib/postgresql/data:rw
      # copy the sql script to create tables
      - ./postgresql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - cw_network
      
  ## NGINX
  nginx:
    container_name: cw_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./project:/var/www/html
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgresql
    networks:
      - cw_network

## Docker Configs
configs:
  nginx:
    file: ./nginx/default.conf
  phplocal:
    file: ./php/local.ini

## Docker Networks
networks:
  cw_network:
    driver: bridge
    name: cw_network

## Docker Volumes
volumes:
  postgresdata: