#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_camper_list:
    path: /
    controller: App\Controller\CamperController::index
app_camper:
    path: /{list_id<\d+>}
    controller: App\Controller\CamperController::show
app_import:
    path: /import
    controller: App\Controller\CamperController::import
app_info:
    path: /info
    controller: App\Controller\CamperController::info